# Copyright (C)  2014 Richard Bäck.
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3 or
# any later version published by the Free Software Foundation; with no
# Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
# copy of the license is included in the section entitled "GNU Free
# Documentation License".

#+TITLE:     Unternehmensrechtsformen
#+AUTHOR:    
#+EMAIL:     
#+DATE:      
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:nil ::nil |:nil ^:nil -:nil f:nil *:nil <:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[margin=1.5cm,vmargin={0pt,1cm}]{geometry}

#+LATEX_HEADER: \setlength{\headheight}{2.5cm}
#+LATEX_HEADER: \setlength{\headsep}{0.5cm}
#+LATEX_HEADER: \setlength{\textheight}{24cm}

#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \lhead{Richard Bäck}
#+LATEX_HEADER: \chead{richard.baeck@openmailbox.org}
#+LATEX_HEADER: \rhead{2014-11-28-Fri}
#+LATEX_HEADER: \lfoot{Unternehmensrechtsformen}
#+LATEX_HEADER: \cfoot{}
#+LATEX_HEADER: \rfoot{Seite \thepage}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}

\thispagestyle{fancy}
- Einzelunternehmer ::
  Sine natürliche Personen, die ein Unternehmen auf ihren Namen laufen
  haben. Sie haften unbeschränkt und müssen selbst eine
  Gewerbeberechtigung besitzen. Sollte sie über dem
  Umsatzschwellenwertkommen, benötigen sie eine Firmenbucheintragung
  (Einzelunternehmer \rightarrow eingetragener Einzelunternehmer).
- Personengesellschaften ::
  - Offene Gesellschaft ::
    Eine OG ist ein Zusammenschluss von 2+ juristischen/natürlichen
    Personen. Die Haftung wird von den Gesellschaftern persönlich,
    unbeschränkt, solidarisch und primär übernommen. Die
    Gewerbeberechtigung muss entweder von einem Gesellschafter oder
    einem Arbeitnehmer übernomen werden.
  - Kommanditgesellschaft ::
    Eine OG besteht aus mindestens einem uneingeschränkt haftenden
    Gesellschafter (= Komplementär) und einem Gesellschafter, der nur mit
    seiner Einlage haftet (= Kommanditist). Die Komplementäre haften
    unbeschränkt, solidarisch und direkt. Die Gewerbeberechtigung ist wie
    bei der OG zu erbringen. Kommanditisten haben nur bei
    außergewöhnlichen Geschäftsfällen ein Mitspracherecht.
  - Stille Gesellschaft ::
    Eine natürliche/juristische Person beteiligt mit einer
    Vermögenseinlage an einer Gesellschaft. Sie hat immer ein Recht auf
    Beteiligung am Gewinn, muss jedoch nicht für einen Verlust
    aufkommen. Sie besitzt ein Kontrollrecht, wie der Kommanditist.
  - Gesellschaft nach bürgerlichem Recht :: Zwei
       juristische/natürliche Personen arbeiten zusammen und teilen
       sich den Gewinn. Dabei muss jeder selber die
       Gewerbeberechtigung erbringen. Bei der Überschreitung des
       Umsatzschwellenwertes wird sie zu einer OG.
- Kapitalgesellschaften :: Immer Bilanzierungspflichtig, benötigen
     immer einen Firmenbucheintrag, Haftung der Gesellschafter geht
     nur auf das eingebrachte Kapital
  - GmbH :: Die GmbH besteht aus einer oder mehreren
            natürlichen/juristischen Personen. Selbst ist sie eine
            juristische Person. Der Gesellschaftsvertrag muss in
            Notariaktsform erbracht werden. GmbHs können de facto mit
            einer Nominale von € 10.000 gegründet werden. Geführt wird
            sie von einem oder mehreren Geschäftsführern. Dieser muss
            ein Gesellschafter sein und wird von der
            Generalversammlung bestellt. Die Generalversammlung ist
            ein Zusammentreffen aller Gesellschafter. Dabei wird auch
            der Aufsichtsrat gewählt. Dieser kontrolliert wiederum den
            Geschäftsführer.
  - AG :: Eine AG ist eine jurisitische Person und besteht aus einen
          oder mehren juristischen/natürlichen Personen (=
          Aktionären). Die Aktionäre haften nur mit ihren
          Einlagen. Zur Gründung muss ein Gesellschaftsvertrag in
          Notarialsaktform und eine Nominale von € 70.000 aufgebracht
          werden. Weiters müssen auch ein Vorstand (=
          Geschäftsführung) und ein Aufsichtsrat bestellt werden. Der
          Vorstand wird von dem Aufsichtsrat
          kontrolliert. Vorstandsmitglieder müssen keine
          Gesellschafter sein, Aufsichtratmitglieder schon. Die
          Hauptversammlung (Versammlung aller Aktionäre) wählt den
          Aufsichtrat auf 4 Jahre.
- Genossenschaft :: Dient nicht zur Gewinnerzielung, sondern zur
                    Förderung des Gewinns ihrer Mitglieder. Eine
                    Genossenschaft kann ein Kapital besitzen und
                    ähnelt in ihrem Aufbau der AG. Außerdem kann sie
                    entweder als /mit beschränkter/ oder /ohne
                    beschränkter/ Haftung bestehen.
