# Copyright (C)  2015 Richard Bäck.
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3 or
# any later version published by the Free Software Foundation; with no
# Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
# copy of the license is included in the section entitled "GNU Free
# Documentation License".

#+TITLE:     Software Lizenzen
#+AUTHOR:    Richard Bäck
#+EMAIL:     richard.baeck@openmailbox.org
#+DATE:      2015-03-03 Tue
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  de
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:

#+startup: beamer
#+startup: beamer
#+BEAMER_FRAME_LEVEL: 2
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+LATEX_HEADER: \mode<beamer>{\usetheme{AnnArbor}\usecolortheme{whale}}
#+LATEX_HEADER: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Aktuelles Thema}\tableofcontents[currentsection]\end{frame}}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)


* Einleitung
** Arten von Lizenzen
- Propietär
- Liberale/freizügige Lizenzen
  - MIT
  - BSD
- Konservative/einschränkende Lizenzen
  - GPL
** Arten von Freiheiten
- Negative Freiheit
  - Eine freie Software kann auf Grund ihrer Lizenz propietär
    verwendet werden
- Positive Freiheit
  - Eine freie Software kann auf Grund ihrer Lizenz nicht propietär
    verwendet werden
* Die BSD Lizenz
** Was ist die BSD Lizenz?
- BSD = Berkley Software Distribution
- Entstanden an der Universtität Berkley/Kalifornien
- Wird für UNIX-Ableger der Berkley Universtität verwendet (FreeBSD,
  OpenBSD, NetBSD, ...)
- Liberale Lizenz
- Negative Freiheit ist gegeben
** Lizenztext der FreeBSD (2-Klausen BSD-) Lizenz
\tiny
#+BEGIN_SRC java
Copyright (c) <YEAR>, <OWNER>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of the FreeBSD Project.
#+END_SRC
* Die GPL
** Was ist die GPL?
- GPL = GNU Public License
- Enstanden durch das GNU Projekt und der freien Softwarebewegung
- Erweiterung ist die AGPL (Affero GPL)
  - Wichtig für Netzwerkdienste \rightarrow Dienstprogramm muss frei
    sein
  - Soll Benutzer von unfreien Diensten (REST-Server etc.) schützen
- Konservative Lizenz
- Positive Freiheit ist gegeben
** Lizenztext (für Quelldateienköpfen) der GPLv3
\scriptsize
#+BEGIN_SRC java
Copyright <YEAR> <OWNER>

This file is part of Foobar.

Foobar is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Foobar is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#+END_SRC
[[http://www.gnu.org/licenses/gpl-3.0.txt]]
* Ende
